// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable 1591, 0612, 3021
namespace enos_subscription.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TransferPkg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TransferPkg()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int cmdId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public byte[] data { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int seqId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool zip
        {
            get { return __pbn__zip.GetValueOrDefault(); }
            set { __pbn__zip = value; }
        }
        public bool ShouldSerializezip()
        {
            return __pbn__zip != null;
        }
        public void Resetzip()
        {
            __pbn__zip = null;
        }
        private bool? __pbn__zip;

        [global::ProtoBuf.ProtoMember(5)]
        public uint ver
        {
            get { return __pbn__ver.GetValueOrDefault(); }
            set { __pbn__ver = value; }
        }
        public bool ShouldSerializever()
        {
            return __pbn__ver != null;
        }
        public void Resetver()
        {
            __pbn__ver = null;
        }
        private uint? __pbn__ver;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AsterPkg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public AsterPkg()
        {
            data = new global::System.Collections.Generic.List<byte[]>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int seqno { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int ackno { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int flag
        {
            get { return __pbn__flag.GetValueOrDefault(); }
            set { __pbn__flag = value; }
        }
        public bool ShouldSerializeflag()
        {
            return __pbn__flag != null;
        }
        public void Resetflag()
        {
            __pbn__flag = null;
        }
        private int? __pbn__flag;

        [global::ProtoBuf.ProtoMember(4)]
        public int wnd
        {
            get { return __pbn__wnd.GetValueOrDefault(); }
            set { __pbn__wnd = value; }
        }
        public bool ShouldSerializewnd()
        {
            return __pbn__wnd != null;
        }
        public void Resetwnd()
        {
            __pbn__wnd = null;
        }
        private int? __pbn__wnd;

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<byte[]> data { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransferAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TransferAck()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PointAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PointAttr()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string key { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SliceTrigger : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SliceTrigger()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool isSame { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public long sliceLen { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KVPair2_0 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public KVPair2_0()
        {
            attrs = new global::System.Collections.Generic.List<PointAttr>();
            sliceTrigger = new global::System.Collections.Generic.List<SliceTrigger>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string point { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string value { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string domain { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<PointAttr> attrs { get; private set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<SliceTrigger> sliceTrigger { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KVPairDevice2_0 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public KVPairDevice2_0()
        {
            datas = new global::System.Collections.Generic.List<KVPair2_0>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<KVPair2_0> datas { get; private set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string device { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KVPairRecord2_0 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public KVPairRecord2_0()
        {
            deviceDatas = new global::System.Collections.Generic.List<KVPairDevice2_0>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public long collectTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<KVPairDevice2_0> deviceDatas { get; private set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public long sendTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KVPair : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public KVPair()
        {
            attrs = new global::System.Collections.Generic.List<PointAttr>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string deviceId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string point { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string value { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<PointAttr> attrs { get; private set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string domain { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KVPairRecord : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public KVPairRecord()
        {
            datas = new global::System.Collections.Generic.List<KVPair>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public long utc { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<KVPair> datas { get; private set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long ts
        {
            get { return __pbn__ts.GetValueOrDefault(); }
            set { __pbn__ts = value; }
        }
        public bool ShouldSerializets()
        {
            return __pbn__ts != null;
        }
        public void Resetts()
        {
            __pbn__ts = null;
        }
        private long? __pbn__ts;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CommonMsgType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ENUM_KVPairRecord2_0")]
        ENUMKVPairRecord20 = 101,
    }

}

#pragma warning restore 1591, 0612, 3021